config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes
  resources :managers
  resources :employees
  resources :customers
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/quote.rb
class Quote < ApplicationRecord
belongs_to :employees
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote_Number, :sales_Person_Id, :sales_Person_Name, :customer_First_Name, :customer_First_Name, :customer_Last_Name)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_with(model: quote, local: true) do |form| %>
  <% if quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quote_Number %>
    <%= form.text_field :quote_Number %>
  </div>

  <div class="field">
    <%= form.label :sales_Person_Id %>
    <%= form.text_field :sales_Person_Id %>
  </div>

  <div class="field">
    <%= form.label :sales_Person_Name %>
    <%= form.text_field :sales_Person_Name %>
  </div>

  <div class="field">
    <%= form.label :customer_First_Name %>
    <%= form.text_field :customer_First_Name %>
  </div>

  <div class="field">
    <%= form.label :customer_First_Name %>
    <%= form.text_field :customer_First_Name %>
  </div>

  <div class="field">
    <%= form.label :customer_Last_Name %>
    <%= form.text_field :customer_Last_Name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Quote number</th>
      <th>Sales person id</th>
      <th>Sales person name</th>
      <th>Customer first name</th>
      <th>Customer first name</th>
      <th>Customer last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote_Number %></td>
        <td><%= quote.sales_Person_Id %></td>
        <td><%= quote.sales_Person_Name %></td>
        <td><%= quote.customer_First_Name %></td>
        <td><%= quote.customer_First_Name %></td>
        <td><%= quote.customer_Last_Name %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form', quote: @quote %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote number:</strong>
  <%= @quote.quote_Number %>
</p>

<p>
  <strong>Sales person id:</strong>
  <%= @quote.sales_Person_Id %>
</p>

<p>
  <strong>Sales person name:</strong>
  <%= @quote.sales_Person_Name %>
</p>

<p>
  <strong>Customer first name:</strong>
  <%= @quote.customer_First_Name %>
</p>

<p>
  <strong>Customer first name:</strong>
  <%= @quote.customer_First_Name %>
</p>

<p>
  <strong>Customer last name:</strong>
  <%= @quote.customer_Last_Name %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>