config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes
  resources :managers
  resources :employees
  resources :customers
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
 has_many :quotes
  has_many :customers
  belongs_to :managers
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:first_Name, :last_Name, :email, :username, :password, :job_Title, :executive_Privilege, :underlying_ID)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_Name %>
    <%= form.text_field :first_Name %>
  </div>

  <div class="field">
    <%= form.label :last_Name %>
    <%= form.text_field :last_Name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :job_Title %>
    <%= form.text_field :job_Title %>
  </div>

  <div class="field">
    <%= form.label :executive_Privilege %>
    <%= form.text_field :executive_Privilege %>
  </div>

  <div class="field">
    <%= form.label :underlying_ID %>
    <%= form.text_field :underlying_ID %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Job title</th>
      <th>Executive privilege</th>
      <th>Underlying id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.first_Name %></td>
        <td><%= employee.last_Name %></td>
        <td><%= employee.email %></td>
        <td><%= employee.username %></td>
        <td><%= employee.password %></td>
        <td><%= employee.job_Title %></td>
        <td><%= employee.executive_Privilege %></td>
        <td><%= employee.underlying_ID %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_Name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @employee.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @employee.password %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @employee.job_Title %>
</p>

<p>
  <strong>Executive privilege:</strong>
  <%= @employee.executive_Privilege %>
</p>

<p>
  <strong>Underlying id:</strong>
  <%= @employee.underlying_ID %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>