config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes
  resources :managers
  resources :employees
  resources :customers
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/manager.rb
class Manager < ApplicationRecord
has_many :employees
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:first_Name, :last_Name, :email, :username, :password, :job_Title, :executive_Id, :underlying_Id)
    end
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/views/managers/_form.html.erb
<%= form_with(model: manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_Name %>
    <%= form.text_field :first_Name %>
  </div>

  <div class="field">
    <%= form.label :last_Name %>
    <%= form.text_field :last_Name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :job_Title %>
    <%= form.text_field :job_Title %>
  </div>

  <div class="field">
    <%= form.label :executive_Id %>
    <%= form.text_field :executive_Id %>
  </div>

  <div class="field">
    <%= form.label :underlying_Id %>
    <%= form.text_field :underlying_Id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Username</th>
      <th>Password</th>
      <th>Job title</th>
      <th>Executive id</th>
      <th>Underlying id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.first_Name %></td>
        <td><%= manager.last_Name %></td>
        <td><%= manager.email %></td>
        <td><%= manager.username %></td>
        <td><%= manager.password %></td>
        <td><%= manager.job_Title %></td>
        <td><%= manager.executive_Id %></td>
        <td><%= manager.underlying_Id %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Back', managers_path %>

app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @manager.first_Name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @manager.last_Name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @manager.email %>
</p>

<p>
  <strong>Username:</strong>
  <%= @manager.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @manager.password %>
</p>

<p>
  <strong>Job title:</strong>
  <%= @manager.job_Title %>
</p>

<p>
  <strong>Executive id:</strong>
  <%= @manager.executive_Id %>
</p>

<p>
  <strong>Underlying id:</strong>
  <%= @manager.underlying_Id %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>