config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes
  resources :managers
  resources :employees
  resources :customers
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cisproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id='header'>
  <h1>Project 4339</h1>
  <%= link_to "Car", cars_path %>
  <%= link_to "Customer", customers_path %>
  <%= link_to "Employee", employees_path %>
  <%= link_to "Manager", managers_path %>
  <%= link_to "Quote", quotes_path %>

  </div>
  
<!-- Alerts-->  
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


<!-- notice about the user being logged in in the top right corner of the navigation bar--> 
<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
    <%= yield %>
  </body>
</html>